[env:esp32s3base]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
;upload_port = COM3
;monitor_port = COM3
upload_protocol = esptool
upload_speed = 115200
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_qspi
board_build.psram_type = qio
monitor_speed = 115200

board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs

build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
    bblanchon/ArduinoJson @ ^7.0.0
    pololu/VL53L0X @ ^1.3.1
    pololu/VL53L1X @ ^1.3.1
    pololu/VL6180X @ ^1.3.1
    sparkfun/SparkFun VL53L5CX Arduino Library @ ^1.0.3
    robtillaart/AS5600 @ ^0.6.1
    bogde/HX711 @ ^0.7.5
    fastled/FastLED @ ^3.6.0
    firechip/usb-host-msc @ ^1.1.4
    # Almacenamiento USB Host (Native ESP-IDF APIs via Wrapper)

[env:esp32s3cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_protocol = esptool
upload_speed = 460800
monitor_speed = 115200
board_build.flash_mode = opi
board_build.arduino.memory_type = opi_opi
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags = 
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=5
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
    ${env:esp32s3base.lib_deps}
